"""empty message

Revision ID: 17a85030cef9
Revises: 3717327e4a3a
Create Date: 2019-01-27 03:31:35.450243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17a85030cef9'
down_revision = '3717327e4a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('owner_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'measurements', 'users', ['owner_id'], ['public_id'])
    op.drop_column('measurements', 'date_modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.drop_column('measurements', 'owner_id')
    # ### end Alembic commands ###
