"""empty message

Revision ID: 66c3f74c40fa
Revises: b8dc714bec1b
Create Date: 2019-02-17 21:44:11.578316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c3f74c40fa'
down_revision = 'b8dc714bec1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('measurements_owner_id_key', 'measurements', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('measurements_owner_id_key', 'measurements', ['owner_id'])
    # ### end Alembic commands ###
