"""empty message

Revision ID: 863b35d90fe1
Revises: 66c3f74c40fa
Create Date: 2019-02-17 21:55:15.188931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863b35d90fe1'
down_revision = '66c3f74c40fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_constraint('measurements_owner_id_fkey', 'measurements', type_='foreignkey')
    op.create_foreign_key(None, 'measurements', 'plants', ['username'], ['sensor_id'])
    op.drop_column('measurements', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('owner_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.create_foreign_key('measurements_owner_id_fkey', 'measurements', 'plants', ['owner_id'], ['sensor_id'])
    op.drop_column('measurements', 'username')
    # ### end Alembic commands ###
